"use client";
import Link from "next/link";
import { Check, ChevronRight, LogOut, MapPin, Package, Plus, UserRound } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { AddressForm } from "@/components/customer/AddressForm";
import { StorefrontShell } from "@/components/customer/StorefrontShell";
import { useStorefront } from "@/components/customer/StorefrontProvider";
import { money } from "@/lib/money";
import type { CustomerAddress, CustomerOrder, CustomerProfile } from "@/models/storefront";
import { apiRequest } from "@/services/apiClient";
import { notifyCustomerSessionChanged } from "@/lib/customerSession";

function AccountLayout({ active, children }: { active: string; children: React.ReactNode }) { const router = useRouter(); const { profile } = useStorefront(); const displayName = [profile?.firstName, profile?.lastName].filter(Boolean).join(" ") || "Culinara customer"; const initial = (profile?.firstName?.[0] ?? profile?.email?.[0] ?? "C").toUpperCase(); return <StorefrontShell compact><main className={`store-container account-page account-page-${active.toLowerCase()}`}><aside className="account-sidebar"><header><span>{initial}</span><div><small>MY ACCOUNT</small><strong>{displayName}</strong><p>{profile?.email ?? profile?.phone ?? "Customer account"}</p></div></header><nav>{[["Profile", "/account", UserRound], ["Orders", "/account/orders", Package], ["Addresses", "/account/addresses", MapPin]].map(([label, href, Icon]) => <Link key={String(href)} className={active === label ? "active" : ""} href={String(href)}><span><Icon size={18}/>{String(label)}</span><ChevronRight/></Link>)}</nav><button className="account-signout" onClick={async () => { await fetch("/api/session/logout", { method: "POST" }); notifyCustomerSessionChanged(); router.replace("/"); router.refresh(); }}><LogOut/>Sign out</button></aside><section>{children}</section></main></StorefrontShell>; }
export function ProfilePage() { const { profile, refreshProfile } = useStorefront(); const [message, setMessage] = useState(""); const [error, setError] = useState(""); if (!profile) return <AccountLayout active="Profile"><div className="store-empty"><UserRound/><h1>Sign in to your account</h1><Link className="store-primary" href="/login?next=/account">Sign in</Link></div></AccountLayout>; async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const f = new FormData(event.currentTarget); try { await apiRequest<CustomerProfile>("me", { method: "PATCH", body: JSON.stringify({ firstName: String(f.get("firstName") || ""), lastName: String(f.get("lastName") || "") || null }) }); await refreshProfile(); setMessage("Profile updated."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to update profile."); } } return <AccountLayout active="Profile"><header className="account-heading"><small>ACCOUNT</small><h1>Your profile</h1><p>Contact and verification state come directly from your account.</p></header><form className="profile-card" onSubmit={submit}><div className="profile-avatar">{(profile.firstName?.[0] ?? profile.email?.[0] ?? "C").toUpperCase()}</div><div className="form-row"><label>First name<input name="firstName" defaultValue={profile.firstName ?? ""} required/></label><label>Last name<input name="lastName" defaultValue={profile.lastName ?? ""}/></label></div><label>Email<input value={profile.email ?? "Not provided"} disabled/></label><label>Phone<input value={profile.phone ?? "Provided during checkout"} disabled/></label><div className="verification-state"><Check/>{profile.emailVerifiedAt || profile.phoneVerifiedAt ? "Account verified" : "Verification will be required at checkout"}</div>{message && <div className="store-success">{message}</div>}{error && <div className="store-error">{error}</div>}<button className="store-primary">Save profile</button></form></AccountLayout>; }
export function OrdersPage() { const [orders, setOrders] = useState<CustomerOrder[]>([]); const [loading, setLoading] = useState(true); useEffect(() => { apiRequest<{ items: CustomerOrder[] }>("me/orders?limit=100").then((page) => setOrders(page.items)).finally(() => setLoading(false)); }, []); return <AccountLayout active="Orders"><header className="account-heading"><small>ORDER HISTORY</small><h1>Your orders</h1><p>Every receipt preserves the exact item and price snapshots used at checkout.</p></header>{loading ? <div className="store-loading"><span/></div> : orders.length ? <div className="account-orders">{orders.map((order) => <Link href={`/order/${order.publicId}`} key={order.publicId}><span className={`order-state state-${order.status.toLowerCase()}`}>{order.status.replaceAll("_", " ")}</span><div><h2>Order #{order.orderNumber ?? order.publicId}</h2><p>{order.branch?.name} · {new Date(order.placedAt).toLocaleDateString("en-PK", { dateStyle: "medium" })}</p></div><strong>{money(order.grandTotal, order.currency)}</strong><ChevronRight/></Link>)}</div> : <div className="store-empty"><Package/><h2>No orders yet</h2><Link className="store-primary" href="/menu">Start an order</Link></div>}</AccountLayout>; }
export function AddressesPage() { const [addresses, setAddresses] = useState<CustomerAddress[]>([]); const [show, setShow] = useState(false); const load = () => apiRequest<CustomerAddress[]>("me/addresses").then(setAddresses); useEffect(() => { void load(); }, []); async function remove(id: string) { if (!window.confirm("Remove this saved address?")) return; await apiRequest(`me/addresses/${id}`, { method: "DELETE" }); await load(); } return <AccountLayout active="Addresses"><header className="account-heading"><small>DELIVERY</small><h1>Saved addresses</h1><p>Coordinates are stored to validate each restaurant’s delivery area.</p><button className="store-primary" onClick={() => setShow(!show)}><Plus/>Add address</button></header>{show && <div className="profile-card"><AddressForm onSaved={async () => { setShow(false); await load(); }}/></div>}<div className="address-list">{addresses.map((address) => <article key={address.id}><span><MapPin/></span><div><h2>{address.label || "Address"}{address.isDefault && <small>Default</small>}</h2><p>{address.recipientName} · {address.phone}</p><p>{address.addressLine1}{address.addressLine2 ? `, ${address.addressLine2}` : ""}, {address.city}</p></div><div>{!address.isDefault && <button onClick={async () => { await apiRequest(`me/addresses/${address.id}/default`, { method: "PUT" }); await load(); }}>Set default</button>}<button onClick={() => void remove(address.id)}>Remove</button></div></article>)}</div></AccountLayout>; }
