"use client";
import Link from "next/link";
import { ArrowRight, Minus, Plus, ShoppingBag, Trash2 } from "lucide-react";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { StorefrontShell } from "@/components/customer/StorefrontShell";
import { useStorefront } from "@/components/customer/StorefrontProvider";
import { money } from "@/lib/money";
import type { CartQuote, CustomerCart } from "@/models/storefront";
import { apiRequest } from "@/services/apiClient";

export function CartPage() { const router = useRouter(); const { cart, branch, profile, fulfillment, setFulfillment, refreshCart } = useStorefront(); const [pendingId, setPendingId] = useState(""); const [coupon, setCoupon] = useState(""); const [quote, setQuote] = useState<CartQuote | null>(null); const [error, setError] = useState(""); const activeQuote = quote ?? cart?.quote;
  async function mutate(path: string, init: RequestInit) { setPendingId(path); setError(""); try { await apiRequest<CustomerCart>(path, init); setQuote(null); await refreshCart(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Cart update failed."); } finally { setPendingId(""); } }
  async function applyCoupon() { if (!cart || !coupon.trim()) return; setPendingId("coupon"); setError(""); try { const next = await apiRequest<CartQuote>("me/cart/coupon/validate", { method: "POST", body: JSON.stringify({ cartId: cart.id, couponCode: coupon.trim() }) }); setQuote(next); window.sessionStorage.setItem("culinara_coupon", coupon.trim()); } catch (reason) { setError(reason instanceof Error ? reason.message : "Coupon could not be applied."); } finally { setPendingId(""); } }
  if (!profile) return <StorefrontShell><main className="store-container cart-page"><div className="store-empty"><ShoppingBag/><h1>Sign in to start your cart</h1><p>Your cart and authoritative price quote are saved to your customer account.</p><Link className="store-primary" href="/login?next=/cart">Sign in to order</Link></div></main></StorefrontShell>;
  if (!cart?.items.length) return <StorefrontShell><main className="store-container cart-page"><div className="store-empty"><ShoppingBag/><h1>Your cart is empty</h1><p>Explore the menu and customize something delicious.</p><Link className="store-primary" href="/menu">Browse menu</Link></div></main></StorefrontShell>;
  return <StorefrontShell compact><main className="store-container cart-page"><header><small>YOUR ORDER</small><h1>Review your cart</h1><p>{branch?.name} · Prices below are quoted by the restaurant.</p></header><div className="cart-layout"><section><div className="cart-fulfillment"><button className={fulfillment === "DELIVERY" ? "active" : ""} onClick={() => void setFulfillment("DELIVERY")}>Delivery</button><button className={fulfillment === "PICKUP" ? "active" : ""} onClick={() => void setFulfillment("PICKUP")}>Pickup</button></div>{cart.items.map((item) => { const line = activeQuote?.lines.find((row) => row.cartItemId === item.id); return <article className="cart-line" key={item.id}><div className="cart-line-mark">{item.itemName.slice(0, 1)}</div><div><h2>{item.itemName}</h2><strong>{item.variantName}</strong>{item.modifiers.map((modifier) => <small key={modifier.optionId}>+ {modifier.name}{modifier.quantity > 1 ? ` × ${modifier.quantity}` : ""}</small>)}{item.specialInstructions && <p>“{item.specialInstructions}”</p>}<button className="remove-line" disabled={Boolean(pendingId)} onClick={() => void mutate(`me/cart/items/${item.id}`, { method: "DELETE" })}><Trash2/>Remove</button></div><div className="cart-line-actions"><strong>{money(line?.total)}</strong><div><button disabled={item.quantity <= 1 || Boolean(pendingId)} onClick={() => void mutate(`me/cart/items/${item.id}`, { method: "PATCH", body: JSON.stringify({ quantity: item.quantity - 1 }) })}><Minus/></button><b>{item.quantity}</b><button disabled={Boolean(pendingId)} onClick={() => void mutate(`me/cart/items/${item.id}`, { method: "PATCH", body: JSON.stringify({ quantity: item.quantity + 1 }) })}><Plus/></button></div></div></article>; })}<Link className="continue-shopping" href="/menu">← Add more items</Link></section><aside className="cart-summary"><h2>Order summary</h2><label>Promo code<div><input value={coupon} onChange={(event) => setCoupon(event.target.value.toUpperCase())} placeholder="Enter code"/><button disabled={pendingId === "coupon"} onClick={() => void applyCoupon()}>Apply</button></div></label>{activeQuote?.coupon && <div className="coupon-applied">Coupon {activeQuote.coupon.code} applied</div>}{error && <div className="store-error">{error}</div>}<dl><div><dt>Subtotal</dt><dd>{money(activeQuote?.subtotal)}</dd></div><div><dt>Discount</dt><dd>-{money(activeQuote?.discount)}</dd></div><div><dt>Delivery fee</dt><dd>{money(activeQuote?.deliveryFee)}</dd></div><div><dt>Tax</dt><dd>{money(activeQuote?.tax)}</dd></div><div><dt>Service fee</dt><dd>{money(activeQuote?.serviceFee)}</dd></div><div className="total"><dt>Total</dt><dd>{money(activeQuote?.grandTotal)}</dd></div></dl><button className="checkout-button" onClick={() => router.push("/checkout")}>Continue to checkout <ArrowRight/></button><small>Final availability and pricing are checked again before placement.</small></aside></div></main></StorefrontShell>;
}
