"use client";
import Link from "next/link";
import { Eye, LockKeyhole, Mail, Phone, UserRound, Utensils } from "lucide-react";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { notifyCustomerSessionChanged } from "@/lib/customerSession";

export function CustomerAuthForm({ mode, next = "/menu" }: { mode: "login" | "register"; next?: string }) {
  const router = useRouter(); const [pending, setPending] = useState(false); const [error, setError] = useState(""); const [show, setShow] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setError(""); const form = new FormData(event.currentTarget); const identity = String(form.get("identity") ?? "").trim(); const response = await fetch(`/api/session/${mode}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...(identity.includes("@") ? { email: identity } : { phone: identity }), password: String(form.get("password") ?? ""), ...(mode === "register" ? { firstName: String(form.get("firstName") ?? "").trim(), lastName: String(form.get("lastName") ?? "").trim() || undefined } : {}) }) }); const payload = await response.json().catch(() => null); if (!response.ok) { setError(payload?.error?.message ?? "Unable to continue."); setPending(false); return; } notifyCustomerSessionChanged(); router.replace(next.startsWith("/") && !next.startsWith("//") ? next : "/menu"); router.refresh(); }
  return <main className="customer-auth"><section><Link className="store-brand" href="/"><span><Utensils size={20}/></span>Culinara</Link><div className="auth-welcome"><small>{mode === "login" ? "WELCOME BACK" : "JOIN CULINARA"}</small><h1>{mode === "login" ? "Your next order is waiting." : "Create your customer account."}</h1><p>{mode === "login" ? "Sign in to use your saved cart, addresses, orders and live tracking." : "Save addresses, build your order and follow every kitchen update."}</p></div></section><section className="customer-auth-panel"><form onSubmit={submit}><header><UserRound/><h2>{mode === "login" ? "Sign in" : "Create account"}</h2><p>{mode === "login" ? "Use your email or phone number." : "It only takes a minute."}</p></header>{mode === "register" && <div className="auth-name-row"><label>First name<span><UserRound/><input name="firstName" required autoComplete="given-name"/></span></label><label>Last name<span><UserRound/><input name="lastName" autoComplete="family-name"/></span></label></div>}<label>Email or phone<span>{mode === "login" ? <Mail/> : <Phone/>}<input name="identity" required autoComplete="username" placeholder="you@example.com"/></span></label><label>Password<span><LockKeyhole/><input name="password" type={show ? "text" : "password"} required minLength={8} autoComplete={mode === "login" ? "current-password" : "new-password"}/><button type="button" onClick={() => setShow(!show)} aria-label="Show password"><Eye/></button></span></label>{error && <div className="store-error">{error}</div>}<button className="auth-submit" disabled={pending}>{pending ? "Please wait…" : mode === "login" ? "Sign in" : "Create my account"}</button><p className="auth-switch">{mode === "login" ? "New to Culinara?" : "Already have an account?"} <Link href={`${mode === "login" ? "/register" : "/login"}?next=${encodeURIComponent(next)}`}>{mode === "login" ? "Create account" : "Sign in"}</Link></p><Link className="business-auth-link" href="/business/login">Opening the business portal? Sign in here</Link></form></section></main>;
}
