"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { Check, ChevronRight, Minus, Plus, Search, ShoppingBag, X } from "lucide-react";
import { StorefrontShell } from "@/components/customer/StorefrontShell";
import { useStorefront } from "@/components/customer/StorefrontProvider";
import { money } from "@/lib/money";
import type { MenuCategory, MenuItem, MenuVariant, PublicMenu } from "@/models/storefront";
import { apiRequest, publicApiRequest } from "@/services/apiClient";

export function MenuExperience() {
  const router = useRouter();
  const { branch, cart, profile, refreshCart, fulfillment, setFulfillment } = useStorefront();
  const [categories, setCategories] = useState<MenuCategory[]>([]); const [loading, setLoading] = useState(true);
  const [query, setQuery] = useState(""); const [activeCategory, setActiveCategory] = useState("all"); const [selected, setSelected] = useState<MenuItem | null>(null);
  useEffect(() => { if (!branch) return; publicApiRequest<PublicMenu>(`branches/${branch.id}/menu`).then((menu) => setCategories(menu.categories)).finally(() => setLoading(false)); }, [branch]);
  const items = useMemo(() => categories.flatMap((category) => category.items.map((item) => ({ ...item, categoryId: category.id, categoryName: category.name }))).filter((item) => (activeCategory === "all" || item.categoryId === activeCategory) && `${item.name} ${item.description ?? ""}`.toLowerCase().includes(query.toLowerCase())), [categories, activeCategory, query]);
  return <StorefrontShell><main className="menu-page"><section className="menu-hero"><div className="store-container"><div><span>ORDER ONLINE</span><h1>{branch?.business.name ?? "Fresh food, made for you"}</h1><p>{branch ? `${branch.name} · ${branch.city}` : "Choose a restaurant to see its live menu."}</p></div><div className="fulfillment-switch"><button className={fulfillment === "DELIVERY" ? "active" : ""} onClick={() => void setFulfillment("DELIVERY")}>Delivery</button><button className={fulfillment === "PICKUP" ? "active" : ""} onClick={() => void setFulfillment("PICKUP")}>Pickup</button></div></div></section>
    <div className="store-container menu-layout"><aside className="category-rail"><h3>Explore menu</h3><button className={activeCategory === "all" ? "active" : ""} onClick={() => setActiveCategory("all")}>All items <span>{categories.reduce((sum, row) => sum + row.items.length, 0)}</span></button>{categories.map((category) => <button key={category.id} className={activeCategory === category.id ? "active" : ""} onClick={() => setActiveCategory(category.id)}>{category.name}<span>{category.items.length}</span></button>)}</aside>
      <section className="menu-results"><div className="menu-toolbar"><label><Search size={18}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search the menu"/></label><p>{branch?.isOpenNow && branch.isAcceptingOrders ? <><i/>Open and accepting orders</> : "Currently unavailable for immediate orders"}</p></div>
        {loading ? <div className="store-loading"><span/><p>Loading the live menu…</p></div> : items.length ? <div className="live-product-grid">{items.map((item) => <article key={item.id} className={`live-product-card ${item.isCombo ? "bundle-card" : ""}`}><div className="live-product-image" style={item.imageUrl ? { backgroundImage: `url(${item.imageUrl})` } : undefined}><span>{item.itemType === "DEAL" ? "DEAL" : item.itemType === "COMBO" ? "COMBO" : "FRESH"}</span></div><div><small>{item.categoryName}</small><h2>{item.name}</h2><p>{item.description || "Prepared fresh when you order."}</p>{item.comboComponents.length > 0 && <div className="bundle-preview">{item.comboComponents.map((component) => <span key={component.variantId}>{component.quantity}× {component.itemName}</span>)}</div>}<footer><strong>{item.isCombo ? "Bundle " : "From "}{money(item.variants[0]?.price)}</strong><button disabled={!item.variants.length} onClick={() => setSelected(item)}>{item.modifierGroups.length || item.variants.length > 1 ? "Customize" : "Add"}<Plus size={16}/></button></footer></div></article>)}</div> : <div className="store-empty"><Search/><h2>No menu items found</h2><p>Try another category or search.</p></div>}
      </section>
      <aside className="menu-cart-preview"><div><ShoppingBag size={20}/><h3>Your order</h3><span>{cart?.items.length ?? 0}</span></div>{cart?.items.length ? <>{cart.items.slice(0, 3).map((item) => <article key={item.id}><span>{item.quantity}×</span><div><strong>{item.itemName}</strong><small>{item.variantName}</small></div></article>)}<div className="preview-total"><span>Total</span><strong>{money(cart.quote.grandTotal, cart.quote.currency)}</strong></div><button onClick={() => router.push("/cart")}>View cart <ChevronRight size={16}/></button></> : <p>Your cart is ready for something delicious.</p>}</aside>
    </div>{selected && <Customizer item={selected} onClose={() => setSelected(null)} onAdded={async () => { setSelected(null); await refreshCart(); }} cartId={cart?.id ?? null} signedIn={Boolean(profile)} branchId={branch?.id ?? ""} fulfillment={fulfillment}/>}</main></StorefrontShell>;
}

function Customizer({ item, cartId, branchId, fulfillment, signedIn, onClose, onAdded }: { item: MenuItem; cartId: string | null; branchId: string; fulfillment: "DELIVERY" | "PICKUP"; signedIn: boolean; onClose: () => void; onAdded: () => Promise<void> }) {
  const router = useRouter(); const [variantId, setVariantId] = useState(item.variants.find((row) => row.isDefault)?.id ?? item.variants[0]?.id ?? ""); const [choices, setChoices] = useState<Record<string, boolean>>({}); const [quantity, setQuantity] = useState(1); const [note, setNote] = useState(""); const [error, setError] = useState(""); const [pending, setPending] = useState(false);
  const variant = item.variants.find((row) => row.id === variantId) as MenuVariant | undefined;
  const selectedOptions = item.modifierGroups.flatMap((group) => group.options.filter((option) => choices[option.id]));
  const unit = Number(variant?.price ?? 0) + selectedOptions.reduce((sum, row) => sum + Number(row.priceDelta), 0);
  function toggle(groupId: string, optionId: string) { const group = item.modifierGroups.find((row) => row.id === groupId)!; setChoices((current) => { const next = { ...current }; if (group.maxSelections === 1) group.options.forEach((option) => { next[option.id] = false; }); const selectedCount = group.options.filter((option) => next[option.id]).length; if (!next[optionId] && selectedCount >= group.maxSelections) return current; next[optionId] = !next[optionId]; return next; }); }
  async function add() { if (!signedIn) { router.push(`/login?next=${encodeURIComponent(`/menu?branch=${branchId}`)}`); return; } const invalid = item.modifierGroups.find((group) => { const count = group.options.filter((option) => choices[option.id]).length; return count < group.minSelections || count > group.maxSelections; }); if (invalid) { setError(`Choose ${invalid.minSelections}${invalid.maxSelections !== invalid.minSelections ? `–${invalid.maxSelections}` : ""} from ${invalid.name}.`); return; } setPending(true); setError(""); try { let activeCartId = cartId; if (!activeCartId) { const cart = await apiRequest<{ id: string }>(`me/cart?branchId=${branchId}&fulfillmentType=${fulfillment}`); activeCartId = cart.id; } await apiRequest("me/cart/items", { method: "POST", body: JSON.stringify({ cartId: activeCartId, variantId, quantity, specialInstructions: note || null, modifiers: selectedOptions.map((option) => ({ optionId: option.id, quantity: 1 })) }) }); await onAdded(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to add this item."); setPending(false); } }
  return <div className="customizer-backdrop" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><section className="customizer"><header><div><small>{item.isCombo ? `${item.itemType} DETAILS` : "CUSTOMIZE YOUR ORDER"}</small><h2>{item.name}</h2></div><button onClick={onClose} aria-label="Close"><X/></button></header><div className="customizer-body"><p>{item.description}</p>{item.comboComponents.length > 0 && <fieldset className="combo-includes"><legend>This {item.itemType.toLowerCase()} includes <span>Fixed selection</span></legend>{item.comboComponents.map((component) => <div key={component.variantId}><span>{component.quantity}×</span><strong>{component.itemName}</strong><small>{component.variantName}</small></div>)}</fieldset>}<fieldset><legend>{item.isCombo ? "Bundle price" : "Choose a size"} <span>Required</span></legend>{item.variants.map((row) => <label key={row.id}><input type="radio" name="variant" checked={variantId === row.id} onChange={() => setVariantId(row.id)}/><span><strong>{row.name}</strong><small>{row.sku}</small></span><b>{money(row.price)}</b></label>)}</fieldset>{item.modifierGroups.map((group) => <fieldset key={group.id}><legend>{group.name}<span>{group.isRequired ? "Required" : "Optional"} · Select {group.minSelections === group.maxSelections ? group.maxSelections : `up to ${group.maxSelections}`}</span></legend>{group.options.map((option) => <label key={option.id}><input type={group.maxSelections === 1 ? "radio" : "checkbox"} name={group.id} checked={Boolean(choices[option.id])} onChange={() => toggle(group.id, option.id)}/><span><strong>{option.name}</strong></span><b>{Number(option.priceDelta) ? `+${money(option.priceDelta)}` : "Included"}</b></label>)}</fieldset>)}<label className="special-note">Special instructions<textarea value={note} maxLength={500} onChange={(event) => setNote(event.target.value)} placeholder="Allergies or preparation requests"/></label>{error && <div className="store-error">{error}</div>}</div><footer><div className="quantity-control"><button onClick={() => setQuantity(Math.max(1, quantity - 1))}><Minus/></button><strong>{quantity}</strong><button onClick={() => setQuantity(Math.min(99, quantity + 1))}><Plus/></button></div><button className="add-cart-button" disabled={pending || !variantId} onClick={() => void add()}>{pending ? "Adding…" : <><Check size={18}/>Add to cart · {money(unit * quantity)}</>}</button></footer></section></div>;
}
